# Book settings
title: Geodynamics with Underworld
author: Louis Moresi 
logo: Diagrams/MundusSubterraneus.png
exclude_patterns: ["README.md", "Notes/*", "Scripts/*"]

latex:
  latex_documents:
    targetname: Geodynamics_with_Underworld.tex

html:
#  home_page_in_navbar option: true
  use_repository_button: true

parse:
  myst_extended_syntax: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


repository:
  url                       : "https://github.com/ANU-RSES-Education/PHYS-3070-Book"  # Online location of your book
  branch                    : "2020"  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  jupyterhub_url: "https://phys3070.rses.geoscience.education"  # The URL for your JupyterHub. 
  notebook_interface: "classic" # "jupyterlab" or "classic"
  binderhub_url:  ""  # The URL of the BinderHub (e.g., https://mybinder.org)

execute:
  exclude_patterns:
    - Part2-Python/Introduction2Python/*
    - Part2-Python/Introduction2VersionControl/*
    - Part2-Python/Mapping/*
    - Part2-Python/NumpyAndScipy/*
    - Part2-Python/NumpyAndScipy/Incomplete/*
    - Part2-Python/Plotting/*
    - Part2-Python/SolveMathProblems/*
    - Part2-Python/SphericalMeshing/*    
    - Part2-Python/SphericalMeshing/CartesianTriangulations/*    
    - Part2-Python/SphericalMeshing/SphericalTriangulations/*    
    - Part2-Python/SphericalMeshing/Litho1pt0/*
    - Part2-Python/SympleSympy/

  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.



# https://phys3070.rses.geoscience.education/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FANU-RSES-Education%2FPHYS-3070-Book&urlpath=tree%2FPHYS-3070-Book%2FFrontPage.md&branch=2020
# https://phys3070.rses.geoscience.education/hub/user-redirect/git-pull?repo=https://github.com/ANU-RSES-Education/PHYS-3070-Book&urlpath=tree/PHYS-3070-Book/FrontPage.md&branch=2020
# https://phys3070.rses.geoscience.education/hub/user-redirect/git-pull?repo=https://github.com/ANU-RSES-Education/PHYS-3070-Book&urlpath=tree/PHYS-3070-Book/Part2-Python/NumpyAndScipy/0-NumpyAndScipy.md&branch=2020